### ISSUE TITLE
Not sure how to use this

### ISSUE THREAD

**Issue by seanastephens** [tgallant/multi-timer#1]
Here is what I did:

```
npm install
node server.js
```

Then visited `localhost:3000` and clicked on "create." I see this:

![image](https://cloud.githubusercontent.com/assets/5893305/23113924/cc39e0c8-f6f8-11e6-980d-174e913bfc1b.png)

Is this expected?

cough cough README.md cough

**Comment by hasanain** [comment]
Yes. Currently there is one hard coded room '/rooms/1234'

**Comment by seanastephens** [comment]
:+1:

#2
